# Generated by Django 5.0.7 on 2024-07-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.SmallIntegerField()),
                ('end_time', models.SmallIntegerField()),
                ('course', models.CharField(max_length=20)),
                ('classroom', models.CharField(max_length=20)),
                ('day_of_the_week', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
